<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class PlanPagoFormRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'plan_pago'=>'bail|min:3|max:100|regex:/^[a-zA-Z ]+$/',
            'descripcion'=>'bail||max:300',
        ];
    }
    public function messages()
    {
        return [
            'plan_pago.min'=>'El nombre del campo Plan de Pago debe de tener mas de 3 caracteres.',
            'plan_pago.regex'=>'El nombre de "Plan de Pago" no debe contener caracteres especiales o numericos.',
        ]; // TODO: Change the autogenerated stub
    }
}
