<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ServicioFormRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            // 'servicio'=>'bail|max:30|min:3|regex:/^[a-zA-Z ]+$/',
            'servicio'=>'bail|max:30|min:3|string',//|regex:/^[a-zA-Z ]+$/',
            'precio'=> 'bail|numeric',
        ];
    }
    public function messages()
    {
        return [
            'servicio.min'=>'El nombre del servicio debe de tener mas de 3 caracteres.',
            'servicio.regex'=>'El campo de Nombre de Servicio no debe contener caracteres especiales.',
            'precio.numeric'=>'El campo precio debe de contener solamente caracteres numericos.',

        ]; // TODO: Change the autogenerated stub
    }
}
