<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class UsuarioFormRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'cod_minsa'=>'bail|max:100|min:3',
            'nombre'=>'bail|min:3|max:35|regex:/^[a-zA-Z ]+$/',
            'apellido'=>'bail|min:3|max:35|regex:/^[a-zA-Z ]+$/',
            'cedula'=>'bail|max:14|regex:[\d{3}\d{6}\d{4}[a-zA-Z]{1}]',
            'telefono'=>'bail|numeric|digits:8|nullable',
            'correo'=>'bail|max:50',
            'dir_foto'/*=>'mimes:jpg,bmp,png'|max:255'*/,
           /* 'contraseña'=>'bail|min:6|max:255',*/
           /* 'ccontraseña'=>'bail|same:contraseña',*/
            'descripcion'=>'bail|max:500',
        ];
    }
    public function messages()
    {
        return [
            'cod_minsa.min'=>'El codigo de Minsa debe ser mayor a 3 caracteres.',
            'nombre.min'=>'El nombre debe ser mayor a 3 caracteres.',
            'nombre.max'=>'El nombre no debe ser mayor a 35 caracteres.',
            'nombre.regex'=>'El campo nombre no puede llevar caracteres especiales o numericos.',
            'apellido.min'=>'El apellido debe ser mayor a 3 caracteres.',
            'apellido.max'=>'El apellido no debe ser mayor a 35 caracteres.',
            'apellido.regex'=>'El campo apellido no puede llevar caracteres especiales o numericos.',
            'cedula.max'=>'La cedula debe contoner solo 14 caracteres.',
            'cedula.regex'=>'El formato de la cedula no es correcto.',
            'telefono.numeric'=>'Este campo solo usa caracteres numericos.',
            'telefono.digits'=>'El numero de telefono debe de contener 8 digitos',
            'contraseña.min'=>'El minimo de caracteres debe ser 6.',
            'ccontraseña.same'=> 'La contraseña no coincide.',
        ]; // TODO: Change the autogenerated stub
    }
}
